### ISSUE TITLE
Chapter 13, T-SQL SAMPLE 11, ring_buffer target problematic

### ISSUE THREAD

**Issue by hhkrohn** [SSIO2017/SSIO2017Samples#1]
As described in https://www.sqlskills.com/blogs/jonathan/why-i-hate-the-ring_buffer-target-in-extended-events/ the use of the ring_buffer to "catch" deadlock events is problematic on "production-like" databases because of length limitations in the XML handling.
A quote from the above about the likely consequence:
> The XML document outputs the events oldest first, so the events that we can’t see are actually the most recently collected events and are the ones that we’d probably want to actually have access to.

**Comment by hhkrohn** [comment]
I forgot to say I used a simple script from https://stackoverflow.com/questions/22825147/how-to-simulate-deadlock-on-sql-server to reliably create a deadlock:
`Msg 1205, Level 13, State 45, Line 59
Transaction (Process ID 89) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.`

**Comment by williamadba** [comment]
Thanks for the info. I too have complaints about the ring_buffer, though it works _most of the time._ In our second edition of this book, we have swapped this particular lab out for a query on the .xel target.
